name: Build and Test on macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install cmake python@3.13 ninja gcc
        python3 -m venv venv
        source venv/bin/activate
        pip install conan

    - name: Create MacOS Conan Profile
      run: |
        mkdir -p ~/.conan2/profiles
        echo "[settings]" > ~/.conan2/profiles/default
        echo "os=Macos" >> ~/.conan2/profiles/default
        echo "arch=armv8" >> ~/.conan2/profiles/default
        echo "build_type=Release" >> ~/.conan2/profiles/default
        echo "compiler=gcc" >> ~/.conan2/profiles/default
        echo "compiler.version=14" >> ~/.conan2/profiles/default
        echo "compiler.libcxx=libstdc++11" >> ~/.conan2/profiles/default
        echo "compiler.cppstd=20" >> ~/.conan2/profiles/default


    - name: Install dependencies and build everything
      run: |
        source venv/bin/activate
        conan install . --build=missing
        conan build .

    # Run C++ tests
    - name: Run C++ Tests
      run: |
        cd build/Release && ctest --output-on-failure

    # Run Python tests
    - name: Run Python Tests
      run: |
        source venv/bin/activate
        export PYTHONPATH=$(pwd)/build/Release:$(pwd)/test:$PYTHONPATH
        python -m unittest test_pysort
