name: Build and Test on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies and set up Conan on Windows
      run: |
        .\scripts\windows\install-deps.ps1

    - name: Build everything
      run: |
        python build.py build

    - name: Run C++ and Python Tests
      run: |
        python build.py test
