name: Build and Test on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        Invoke-Expression "&([scriptblock]::Create((iwr -useb get.scoop.sh)))"
        scoop install cmake python ninja gcc
        echo "KEK NINJA VERSION: $(ninja --version)"
        echo "KEK NINJA IS HERE: $((Get-Command ninja).Source)"
        python -m venv venv
        venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install conan

    - name: Create Windows Conan Profile
      run: |
        venv\Scripts\Activate.ps1
        echo "Checking scoop version: $(scoop --version)"
        echo "Checking cmake version: $(cmake --version)"
        mkdir -p $env:USERPROFILE\.conan2\profiles
        echo [settings] > $env:USERPROFILE\.conan2\profiles\default
        echo os=Windows >> $env:USERPROFILE\.conan2\profiles\default
        echo arch=x86_64 >> $env:USERPROFILE\.conan2\profiles\default
        echo build_type=Release >> $env:USERPROFILE\.conan2\profiles\default
        echo compiler=gcc >> $env:USERPROFILE\.conan2\profiles\default
        echo compiler.version=14 >> $env:USERPROFILE\.conan2\profiles\default
        echo compiler.libcxx=libstdc++11 >> $env:USERPROFILE\.conan2\profiles\default
        echo compiler.cppstd=20 >> $env:USERPROFILE\.conan2\profiles\default
        echo [conf] >> $env:USERPROFILE\.conan2\profiles\default
        echo tools.cmake.cmaketoolchain:generator=Ninja >> $env:USERPROFILE\.conan2\profiles\default
        echo tools.cmake.cmaketoolchain:make_program=$((Get-Command ninja).Source) >> $env:USERPROFILE\.conan2\profiles\default
        conan profile show


    - name: Install dependencies and build everything
      run: |
        venv\Scripts\Activate.ps1
        conan install . --build=missing
        conan build .

    - name: Run C++ Tests
      run: |
        cd build\Release && ctest --output-on-failure

    - name: Run Python Tests
      run: |
        venv\Scripts\Activate.ps1
        $env:PYTHONPATH = "$PWD\build\Release;$PWD\test;$PYTHONPATH"
        python -m unittest test_pysort
